#!/usr/bin/env python3
"""
MusicDirector for the episode-scoring skill.

Analyzes script.story semantics and produces a music cue timeline:
  - Detects emotional arc from dialogue, scene tags and character actions.
  - Decides when BGM should play / stop / fade.
  - Maps each segment to a mood keyword (e.g. cheerful, tense, sad).
  - Writes a `music_cues.json` manifest that dula-engine/tools/generate_audio.py
    can consume directly.

The director never blocks the pipeline: if no suitable music file exists, it
falls back to a procedural placeholder generated by generate_music.py.
"""

import json
import os
import re
import sys
from dataclasses import dataclass, field
from typing import List, Dict, Optional

# ─────────────────────────────────────────────────────────────────────────────
# Emotion lexicons (Chinese-first, English fallback)
# ─────────────────────────────────────────────────────────────────────────────

MOOD_PATTERNS_ZH = {
    "cheerful": {
        "words": ["哈哈", "嘿嘿", "嘻嘻", "开心", "高兴", "太好", "棒", "耶", "好玩", "有趣", "期待"],
        "weight": 1.0,
    },
    "excited": {
        "words": ["哇", "太棒", "超酷", "厉害", "惊人", "不可思议", "冲啊", "加油"],
        "weight": 1.1,
    },
    "sad": {
        "words": ["呜", "呜呜", "难过", "伤心", "哭", "眼泪", "失落", "孤单", "可惜", "遗憾"],
        "weight": 1.0,
    },
    "tense": {
        "words": ["糟糕", "完了", "快跑", "危险", "救命", "害怕", "恐惧", "小心", "紧张"],
        "weight": 1.2,
    },
    "angry": {
        "words": ["哼", "生气", "讨厌", "可恶", "混蛋", "烦", "火大", "怒", "气死"],
        "weight": 1.1,
    },
    "mysterious": {
        "words": ["秘密", "奇怪", "诡异", "神奇", "魔法", "未知", "竟然", "难道"],
        "weight": 1.0,
    },
    "romantic": {
        "words": ["喜欢", "爱", "心动", "温柔", "美好", "幸福", "亲爱"],
        "weight": 0.9,
    },
    "proud": {
        "words": ["当然", "没问题", "交给我", "厉害", "看我的", "肯定", "自豪"],
        "weight": 0.9,
    },
    "calm": {
        "words": ["没关系", "别怕", "慢慢来", "没事", "放心", "安静", "休息"],
        "weight": 0.8,
    },
}

MOOD_PATTERNS_EN = {
    "cheerful": {
        "words": ["haha", "yay", "great", "happy", "awesome", "fun", "joy"],
        "weight": 1.0,
    },
    "excited": {
        "words": ["wow", "amazing", "cool", "incredible", "excited", "let's go"],
        "weight": 1.1,
    },
    "sad": {
        "words": ["sob", "sad", "cry", "sorry", "lonely", "upset", "tears"],
        "weight": 1.0,
    },
    "tense": {
        "words": ["run", "danger", "help", "scared", "afraid", "hurry", "watch out"],
        "weight": 1.2,
    },
    "angry": {
        "words": ["angry", "hate", "damn", "annoying", "mad", "furious"],
        "weight": 1.1,
    },
    "mysterious": {
        "words": ["secret", "strange", "magic", "mystery", "weird", "unknown"],
        "weight": 1.0,
    },
    "romantic": {
        "words": ["love", "like", "heart", "sweet", "dear", "romantic"],
        "weight": 0.9,
    },
    "proud": {
        "words": ["of course", "leave it", "definitely", "sure", "proud"],
        "weight": 0.9,
    },
    "calm": {
        "words": ["it's okay", "don't worry", "calm", "gentle", "relax"],
        "weight": 0.8,
    },
}

# Scene-level mood hints
SCENE_MOOD_HINTS = {
    "room": "calm",
    "classroom": "calm",
    "park": "cheerful",
    "forest": "mysterious",
    "cave": "tense",
    "space": "mysterious",
    "battle": "tense",
    "chase": "tense",
    "party": "cheerful",
    "rain": "sad",
    "sunset": "romantic",
    "night": "mysterious",
}

ACTION_MOOD_HINTS = {
    "jumpforjoy": "excited",
    "run": "tense",
    "cry": "sad",
    "shout": "angry",
    "scared": "tense",
    "surprisedjump": "excited",
    "claphands": "cheerful",
    "wavehand": "cheerful",
    "tremble": "tense",
    "hide": "tense",
    "hug": "romantic",
}


@dataclass
class Segment:
    index: int
    start: float
    end: float
    character: Optional[str]
    dialogue: str
    scene: Optional[str] = None
    actions: List[str] = field(default_factory=list)
    moods: Dict[str, float] = field(default_factory=dict)


class MusicDirector:
    """Rule-based semantic music director."""

    def __init__(self, language="auto"):
        self.language = language

    # ─────────────────────────────────────────────────────────────────────────
    # Public API
    # ─────────────────────────────────────────────────────────────────────────

    def analyze_story(self, text: str) -> List[Segment]:
        """Parse script.story and return scored segments."""
        segments = self._parse_story(text)
        for seg in segments:
            seg.moods = self._score_segment(seg)
        return segments

    def build_cue_timeline(
        self,
        segments: List[Segment],
        default_mood: str = "calm",
        min_music_duration: float = 3.0,
        gap_threshold: float = 2.0,
    ) -> List[Dict]:
        """
        Convert segments into BGM cues.

        Rules:
          - Merge consecutive segments with the same dominant mood.
          - Drop music during very short neutral gaps (keep ambience continuous).
          - Insert a Stop cue after the last spoken segment if trailing silence > gap_threshold.
        """
        if not segments:
            return []

        # Resolve a dominant mood for each segment
        resolved = []
        for seg in segments:
            mood = self._dominant_mood(seg.moods) or default_mood
            resolved.append((seg, mood))

        cues = []
        current_mood = None
        current_start = 0.0
        current_end = 0.0

        for i, (seg, mood) in enumerate(resolved):
            # Scene-level default can override empty dialogue segments
            if not mood or mood == "neutral":
                mood = self._scene_default_mood(seg.scene) or default_mood

            if mood != current_mood:
                # Close previous cue
                if current_mood and (current_end - current_start) >= min_music_duration:
                    cues.append(self._make_play_cue(current_mood, current_start, current_end))
                current_mood = mood
                current_start = seg.start
                current_end = seg.end
            else:
                current_end = max(current_end, seg.end)

        # Close final cue
        if current_mood and (current_end - current_start) >= min_music_duration:
            cues.append(self._make_play_cue(current_mood, current_start, current_end))

        # Add explicit stop after the story ends if requested by later logic
        return cues

    # ─────────────────────────────────────────────────────────────────────────
    # Parsing
    # ─────────────────────────────────────────────────────────────────────────

    @staticmethod
    def _parse_story(text: str) -> List[Segment]:
        lines = text.replace("\r\n", "\n").replace("\r", "\n").split("\n")
        segments = []
        i = 0
        current_scene = None
        while i < len(lines):
            if lines[i].strip() == "":
                i += 1
                continue
            try:
                index = int(lines[i].strip())
            except ValueError:
                i += 1
                continue
            i += 1
            if i >= len(lines):
                break
            time_line = lines[i].strip()
            i += 1
            m = re.match(
                r"(\d{2}):(\d{2}):(\d{2}),(\d{3})\s+-->\s+(\d{2}):(\d{2}):(\d{2}),(\d{3})",
                time_line,
            )
            if not m:
                continue
            start = (
                int(m.group(1)) * 3600
                + int(m.group(2)) * 60
                + int(m.group(3))
                + int(m.group(4)) / 1000
            )
            end = (
                int(m.group(5)) * 3600
                + int(m.group(6)) * 60
                + int(m.group(7))
                + int(m.group(8)) / 1000
            )
            text_lines = []
            while i < len(lines) and lines[i].strip() != "":
                text_lines.append(lines[i].strip())
                i += 1
            content = "\n".join(text_lines)

            # Scene tag @SceneName{...}
            scene_match = re.search(r"^@(\w+)", content)
            if scene_match:
                current_scene = scene_match.group(1)

            char_match = re.search(r"\[(\w+)\]", content)
            character = char_match.group(1) if char_match else None

            dialogue = re.sub(r"^@\w+(?:\{[^}]*\})*\s*", "", content)
            dialogue = re.sub(r"\[\w+\]\s*", "", dialogue)
            dialogue = re.sub(r"\{[A-Za-z]+:[^}]+\}\s*", "", dialogue).strip()

            actions = re.findall(r"\}[A-Z][a-zA-Z]+(?:\{|$|\s)", content)
            actions = [re.sub(r"[\}\{\s]", "", a).lower() for a in actions]

            segments.append(
                Segment(
                    index=index,
                    start=start,
                    end=end,
                    character=character,
                    dialogue=dialogue,
                    scene=current_scene,
                    actions=actions,
                )
            )
        return segments

    # ─────────────────────────────────────────────────────────────────────────
    # Scoring
    # ─────────────────────────────────────────────────────────────────────────

    def _score_segment(self, seg: Segment) -> Dict[str, float]:
        moods = {}
        lang = self._detect_language(seg.dialogue)
        patterns = MOOD_PATTERNS_ZH if lang == "zh" else MOOD_PATTERNS_EN

        # Dialogue keywords
        for mood, data in patterns.items():
            score = 0.0
            for word in data["words"]:
                if lang == "zh":
                    score += seg.dialogue.count(word)
                else:
                    score += len(re.findall(rf"\b{re.escape(word)}\b", seg.dialogue, re.IGNORECASE))
            if score > 0:
                moods[mood] = moods.get(mood, 0.0) + score * data["weight"]

        # Punctuation boost
        if re.search(r"[!！]{2,}", seg.dialogue):
            moods["excited"] = moods.get("excited", 0.0) + 0.5
        if re.search(r"[?？]{2,}", seg.dialogue):
            moods["mysterious"] = moods.get("mysterious", 0.0) + 0.3
        if re.search(r"\.{3,}|…{1,}", seg.dialogue):
            moods["sad"] = moods.get("sad", 0.0) + 0.3

        # Scene hint
        scene_mood = self._scene_default_mood(seg.scene)
        if scene_mood:
            moods[scene_mood] = moods.get(scene_mood, 0.0) + 0.4

        # Action hints
        for action in seg.actions:
            if action in ACTION_MOOD_HINTS:
                m = ACTION_MOOD_HINTS[action]
                moods[m] = moods.get(m, 0.0) + 0.5

        return moods

    @staticmethod
    def _detect_language(text: str) -> str:
        chinese = len(re.findall(r"[\u4e00-\u9fff]", text))
        english = len(re.findall(r"[a-zA-Z]", text))
        if chinese > english and chinese > 0:
            return "zh"
        if english > chinese and english > 0:
            return "en"
        return "zh"

    @staticmethod
    def _dominant_mood(moods: Dict[str, float], threshold: float = 0.5) -> Optional[str]:
        if not moods:
            return None
        best = max(moods.items(), key=lambda x: x[1])
        return best[0] if best[1] >= threshold else "neutral"

    @staticmethod
    def _scene_default_mood(scene: Optional[str]) -> Optional[str]:
        if not scene:
            return None
        scene_lower = scene.lower()
        for key, mood in SCENE_MOOD_HINTS.items():
            if key in scene_lower:
                return mood
        return None

    @staticmethod
    def _make_play_cue(mood: str, start: float, end: float) -> Dict:
        return {
            "action": "Play",
            "mood": mood,
            "startTime": round(start, 3),
            "endTime": round(end, 3),
            "fadeIn": 1.5,
            "fadeOut": 2.0,
            "baseVolume": 0.45,
        }


# ─────────────────────────────────────────────────────────────────────────────
# CLI entry point
# ─────────────────────────────────────────────────────────────────────────────

def main():
    import argparse

    parser = argparse.ArgumentParser(description="Generate semantic BGM cues for an episode.")
    parser.add_argument("episode", help="Path to episode directory containing script.story")
    parser.add_argument("--output", "-o", help="Output JSON path", default=None)
    parser.add_argument("--default-mood", default="calm", help="Fallback mood when no emotion is detected")
    parser.add_argument("--min-duration", type=float, default=3.0, help="Minimum cue duration in seconds")
    args = parser.parse_args()

    episode = os.path.abspath(args.episode)
    story_path = os.path.join(episode, "script.story")
    if not os.path.exists(story_path):
        print(f"[MusicDirector] script.story not found: {story_path}")
        sys.exit(1)

    with open(story_path, "r", encoding="utf-8") as f:
        story_text = f.read()

    director = MusicDirector()
    segments = director.analyze_story(story_text)
    cues = director.build_cue_timeline(segments, default_mood=args.default_mood, min_music_duration=args.min_duration)

    # Print mood summary
    print(f"[MusicDirector] Analyzed {len(segments)} segments, generated {len(cues)} cue(s):")
    for cue in cues:
        print(f"  {cue['startTime']:>7.2f}s - {cue['endTime']:>7.2f}s  {cue['mood']}")

    output_path = args.output or os.path.join(episode, "assets", "audio", "music_cues.json")
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump({"cues": cues, "version": 1}, f, ensure_ascii=False, indent=2)
    print(f"[MusicDirector] Wrote {output_path}")


if __name__ == "__main__":
    main()
