#!/bin/bash
# E05 seg2 keyframes: riverbank block -- frame_11..frame_25 + I2V first
# frame (run_bank). Codex imagegen; morning masters + seg1 frames first.
# Boy design lock comes from assets/boy_reference.png (sunprint master,
# generated by gen_masters.sh) -- never from xiaoju_secret art directly.
# Expressions are written LAYERED (brows/eyes/mouth). Idempotent.
set -u
cd "D:/opensource/movie/dula-story/episodes/cat_leads_e05_morning_sketch"
mkdir -p assets/keyframes assets/action_inbetweens tmp

A="D:/opensource/movie/dula-story/episodes/cat_leads_e05_morning_sketch/assets"
K="$A/keyframes"
FLAGS="--skip-git-repo-check --ephemeral -s workspace-write"

LOCK="Style lock: original illustration style \"sunprint\" -- razor-clean flat color shapes like a high-definition retro silkscreen poster with zero texture, zero grain, zero noise. Shadows everywhere use complementary colors (lavender #8E7CC3, teal-green), never black or grey. Characters in crisp cel-style flat color with one shadow layer; outlines warm brown on the lit side, muted purple on the shadow side. Avoid: stepped or striped sky, banding, grain, noise, paper texture, halftone, airbrush, blur, photorealism, 3D render, lens flare, glow effects, Makoto Shinkai style, text, captions, logos, watermark, signature."

MORNING="Time-of-day override: clear summer morning, about 6am, just after sunrise. Sky: fresh morning cyan blue (#3E9BD8) at the top softening into peach gold (#FFC07A) near the horizon through ONE wide soft transition band (the only soft gradient allowed), with one brighter flat gold (#F5B942) band low over the horizon. The sun is a low flat pale-gold disc (#FFD97A) low in the RIGHT side of the sky (east), hard-edged, no halo. Warm gold sunlight rakes in from frame RIGHT; shadows are long and slanted, all pointing toward frame LEFT (west); shadow side stays lavender (#8E7CC3), never pure black. Dew drops on grass and leaf tips are tiny flat white four-point sparkle shapes (#FDFBF4), hard-edged, sparse. No glow, no halo, no haze, no mist."

GIRL="The girl: slim 16-year-old, large amber eyes, long straight deep-blue hair to her waist, straight bangs, white short-sleeve school shirt, navy-blue plaid pleated skirt, black knee socks, black loafers, no bag no umbrella."
CAT="The cat: orange tabby with darker stripes, white chest patch, four white paws, green eyes, dry fluffy fur, small body."
BOY="The boy: slim 17-year-old, warm light skin, short black hair with slightly messy fringe, dark gray eyes, white short-sleeve school shirt, navy-blue trousers, white sneakers, a kraft-paper-cover sketchbook and one pencil."
AVOID="Avoid: extra people or cats, duplicate limbs, malformed hands, glowing dots, haze, mist, text, watermark, photorealism, 3D render."

gen() { # name prompt refs...
  local name="$1" prompt="$2"; shift 2
  if [ -s "$K/$name.png" ]; then echo "== skip $name (exists)"; return 0; fi
  echo "== gen $name"
  local log="tmp/seg2_$name.log"
  codex exec "$prompt $LOCK $MORNING $AVOID Save the final PNG to $K/${name}.png" $FLAGS "$@" > "$log" 2>&1
  if [ -s "$K/$name.png" ]; then echo "== ok $name"; else echo "== MISSING $name (see $log)"; fi
}

gen frame_11 "Use case: keyframe (base for a lip-sync talking shot). Close-up on the morning riverbank path: $GIRL facing frame RIGHT, arms relaxed at her sides. Expression: eyebrows lifted high; eyes narrowed a little as if recognizing someone far away, gaze locked toward the RIGHT distance; mouth slightly parted. Warm gold rim light on her hair from frame RIGHT. Composition: 16:9 landscape, her face on the left half, soft morning riverbank shapes on the right." \
  -i "$A/girl_reference.png" -i "$K/frame_10.png"

gen frame_run_03 "Use case: I2V first frame for a cat running shot. On the same morning riverbank grass slope: $CAT It stands alert on the LEFT third of the frame, body facing RIGHT, tail high, one front paw lifted about to run, head looking right toward the concrete steps visible far right. The RIGHT two-thirds of the frame is open grass slope descending gently with sparse dew sparkles, kept clear for the cat to run into. Composition: 16:9 landscape, eye-level side view, camera fixed." \
  -i "$A/cat_reference.png" -i "$K/frame_10.png"

gen frame_13 "Use case: keyframe, first clear boy reveal. Medium shot on the morning riverbank steps: $BOY He sits on the low concrete steps, sketchbook open on his knees, turning his head back over his shoulder toward frame LEFT. Expression: eyebrows relaxed; eyes soft with small round catchlights, gaze toward frame LEFT; mouth in a gentle closed-lip smile, right corner slightly higher. $CAT The cat is just arriving at his feet, tail high. Warm gold rim from frame RIGHT on his fringe. Composition: 16:9 landscape, boy center-right, cat small at lower left." \
  -i "$A/boy_reference.png" -i "$A/cat_reference.png" -i "$K/frame_10.png"

gen frame_14 "Use case: keyframe (base for a lip-sync talking shot). Close-up on the same steps: $BOY sitting, body facing frame LEFT, looking down at the cat at his feet (out of frame). Expression: eyebrows level and relaxed; upper eyelids slightly lowered, gaze soft downward-left; mouth closed in a faint warm symmetric smile. Composition: 16:9 landscape, boy on the right half, soft morning grass shapes behind." \
  -i "$A/boy_reference.png" -i "$K/frame_13.png"

gen frame_15 "Use case: keyframe. Close-up on the same steps: $BOY He looks up toward frame LEFT (toward the girl, out of frame), frozen mid-motion, pencil paused above the sketchbook page. Expression: eyebrows raised high; eyes wide, gaze up-left; mouth slightly parted in surprise. Composition: 16:9 landscape, same camera as the adjacent boy close-ups." \
  -i "$A/boy_reference.png" -i "$K/frame_14.png"

gen frame_16 "Use case: keyframe (base for a lip-sync talking shot). Close-up on the same steps: $BOY sitting, body facing frame LEFT, one hand raised to the back of his head mid-scratch, elbow out. Expression: eyebrows slightly raised and uneven; gaze darting down then back up toward frame LEFT; mouth in a small sheepish closed smile. Composition: 16:9 landscape, boy on the right half, morning riverbank soft shapes behind." \
  -i "$A/boy_reference.png" -i "$K/frame_15.png"

gen frame_17 "Use case: keyframe, two-shot. Medium shot on the morning riverbank steps: $GIRL stands at frame LEFT leaning in slightly, and $BOY seated on the steps turns the open sketchbook toward her to show it; $CAT the cat sits on the step between them, looking up at the girl. Warm gold morning light, long lavender shadows to the left. Composition: 16:9 landscape, girl left, boy right, cat center-low." \
  -i "$A/girl_reference.png" -i "$A/boy_reference.png" -i "$A/cat_reference.png"

gen frame_18 "Use case: insert close-up. An open kraft-paper-cover sketchbook held at a slight angle by a boy's hand at the lower edge: the page is filled with many small pencil-style studies of the same orange tabby cat (sitting, stretching, sleeping curled, tail high), rendered as simple flat grey-lavender line drawings on warm cream paper, no text, no readable characters. Composition: 16:9 landscape, sketchbook fills the center, morning grass flat shapes at the edges." \
  -i "$A/cat_reference.png" -i "$K/frame_17.png"

gen frame_19 "Use case: keyframe (base for a lip-sync talking shot). Close-up on the same steps: $BOY sitting, body facing frame LEFT, one hand resting on the sketchbook on his knees. Expression: eyebrows relaxed and slightly raised; eyes bright and open with round catchlights, gaze toward frame LEFT; mouth in an open warm smile. Composition: 16:9 landscape, boy on the right half." \
  -i "$A/boy_reference.png" -i "$K/frame_16.png"

gen frame_20 "Use case: keyframe. High-angle medium shot on the morning riverbank grass: $GIRL standing, looking down at $CAT the cat sitting at her feet looking back up at her; sparse dew sparkles on the grass tips around them. Composition: 16:9 landscape, girl upper-left of center, cat lower-right, both seen from a gentle high angle." \
  -i "$A/girl_reference.png" -i "$A/cat_reference.png" -i "$K/frame_10.png"

gen frame_21 "Use case: keyframe (base for a lip-sync talking shot). Close-up: $GIRL looking down toward frame LEFT at the cat below. Expression: eyebrows level and soft; upper eyelids slightly lowered, gaze gentle downward-left; mouth closed in a tender asymmetric smile, left corner slightly higher. Warm gold rim on her hair from frame RIGHT. Composition: 16:9 landscape, her face on the right half, soft morning shapes on the left." \
  -i "$A/girl_reference.png" -i "$K/frame_20.png"

gen frame_22 "Use case: keyframe. Medium shot on the morning riverbank steps: $CAT the cat lands neatly on the concrete step between the seated boy and the standing girl, tail high, front paws together; the boy's white-shirted side at frame RIGHT edge, the girl's skirt and legs at frame LEFT edge. Composition: 16:9 landscape, cat center, low eye-level." \
  -i "$A/cat_reference.png" -i "$K/frame_17.png"

gen frame_23 "Use case: keyframe (base for a lip-sync talking shot). Close-up: $CAT sitting upright on the concrete step, front paws together, head in a three-quarter view toward the camera (mouth clearly visible, closed); expression: chin slightly lifted, eyes narrowed to contented slits, ears upright -- a quietly proud look. Warm gold rim on its back from frame RIGHT. Composition: 16:9 landscape, cat center, soft step edges behind." \
  -i "$A/cat_reference.png" -i "$K/frame_22.png"

gen frame_24 "Use case: keyframe, wide finale. Very wide shot of the morning riverbank: the boy and the girl sit side by side on the low concrete steps with a small gap between them where the orange tabby cat sits upright, all three facing frame RIGHT toward the river and the low morning sun; long lavender shadows stretch behind them toward frame LEFT; grass with sparse dew sparkles; the river carries a peach-gold band. Composition: 16:9 landscape, trio small on the lower-right third, river and morning sky fill the frame." \
  -i "$A/girl_reference.png" -i "$A/boy_reference.png" -i "$A/cat_reference.png"

gen frame_25 "Use case: closing shot. Pure morning sky: fresh cyan blue with ONE wide soft transition band to peach gold near the bottom, the low flat pale-gold sun disc, a few hard-edged rounded white clouds with a single flat lavender shadow tone, and a thin sliver of grass with sparse dew sparkles along the very bottom edge. No people, no cat, no text. Composition: 16:9 landscape, camera tilted up." \
  -i "$A/scene_riverbank_morning.png"

echo "== seg2 done"
